# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.0

jobs:
  "golang-1.11": &template
    docker:
      # https://circleci.com/docs/2.0/configuration-reference/#setup_remote_docker
      - image: circleci/golang:1.11

    # https://circleci.com/docs/2.0/configuration-reference/#resource_class
    resource_class: xlarge

    # Leave working directory unspecified and use defaults:
    # https://circleci.com/blog/go-v1.11-modules-and-circleci/
    # working_directory: /go/src/github.com/golang-migrate/migrate

    environment:
      GO111MODULE: "on"

    steps:
      - setup_remote_docker:
          version: 18.09.3
          docker_layer_caching: true
      - restore_cache:
          keys:
            - go-mod-v1-{{ arch }}-{{ .Branch }}-{{ checksum "go.sum" }}
      - run: "curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1"
      - checkout
      - run: golangci-lint run
      - run: make test COVERAGE_DIR=/tmp/coverage
      - save_cache:
          key: go-mod-v1-{{ arch }}-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  "golang-1.12":
    <<: *template
    docker:
      - image: circleci/golang:1.12

workflows:
  version: 2
  build:
    jobs:
      - "golang-1.11"
      - "golang-1.12"
